RNPushNotificationAndroid/src/main/java/com/dieam/reactnativepushnotification/ReactNativePushNotificationPackage.java

fix: crash when used in conjunction with the app indexing
(If you call the "onNewIntent" in "Activity.onCreate")
https://developers.google.com/app-indexing/android/app?hl=en
Android 5.1.1
react-native 0.17

fix: crash when used in conjunction with the app indexing

---

RNPushNotificationAndroid/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java
RNPushNotificationAndroid/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java

PushNotificationsIOS delivers notifications to your react-native app even when it's not in the foreground. 
This update enables similar behaviour for Android. Additionally, it doesn't display a notification in the drawer if the message is blank. The use case for this is background-fetch.

Android background notifications

---

index.js

It seems that when sending a message like: 
`{
"to" : "bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...", 
"priority" : "normal", 
"notification" : {
"body" : "This week’s edition is now available.", 
"title" : "NewsMagazine.com", 
"icon" : "new", 
}, 
"data" : { 
"volume" : "3.21.15", 
"contents" : "http://www.news-magazine.com/world-week/21659772" 
} 
} 
`
It doesn't extract the "data" the "data" is getting "splat" and therefore  typeof data.data === 'undefined'

bug fix doens't extract the payload data on android

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java

Calling `cancelAll()` will remove all notifications currently in the notification drawer.
Related to #25.

Do not call `cancelAll()` when the message is blank, return only

---

android/build.gradle

Hey,
I keep running into this issue trying to compile this with my app:
> failed to find Build Tools revision 23.0.2
After some trial and error I finally noticed that 23.0.2 is above the version that [React-Native itself uses](https://github.com/facebook/react-native/blob/ce1261a3dd2ac4a526b92689cd1e07e8af2d85ef/local-cli/generator-android/templates/src/app/build.gradle#L81). Can we lower the dependency here to match?
Thanks!

Lower the build tools dependency to match react-native's

---

index.js

When sending local notifications in iOS, the ```.onNotification``` handler passed during configuration was not being called.
The issue is that, on ```Notifications.configure``` in index.js, the ```localNotification``` event described in [React-Native's PushNotificationiOS](https://facebook.github.io/react-native/docs/pushnotificationios.html#addeventlistener) was not given a listener.
Also, for iOS local notifications, you are currently not able to give a ```userInfo``` object. This PR fixes that issue as well.

Add missing iOS Local Notification event listener

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java

When building a VoIP app, for user to be able to receive the call anytime we used to maintain a persistent connection between the app and the VoIP server even when the app is either in the background or get destroyed. This however drains the battery really fast and is also complicated to implement background services. On iOS it provides **PushKit** for this special circumstance while the only way to achieve the same thing on Android is using GCM high priority messages.
Instead of waking up the app in the background for re-regiser to VoIP server when push notifications arrives we restart the react native activity to the foreground when receiving push notification with specific payload `"autoRestartReactActivity"="true"`.
**It will not affect the original behaviour as long as …

Restart React Native when app is destroyed via push notification

---

index.js

When popInitialNotification is true and app is closed, clicking on a notification causes an app crash

Add missing this binding to popInitialNotification callback

---

android/build.gradle
android/src/main/java/com/dieam/reactnativepushnotification/ReactNativePushNotificationPackage.java
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java

This is a potential upgrade to 0.29.  Since what RNPushNotification really needs in its constructor is the Application object, I just pass this in instead of the activity and use getCurrentActivity in getConstants().
And now the MainApplication.java looks like this
```
public class MainApplication extends Application implements ReactApplication {
private Application mApplication = this;
private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
@Override
protected boolean getUseDeveloperSupport() {
return BuildConfig.DEBUG;
}
@Override
protected List<ReactPackage> getPackages() {
return Arrays.<ReactPackage>asList(
new MainReactPackage(),
new ReactNativePushNotificationPackage(mApplication)
);
}
};
...
```

Upgrading to react-native 0.29

---

component/index.js

When running unit tests against a codebase that imports `react-native-push-notification`, the test fails because it's not able to import `./component`.
Create a dummy file to fix broken import. Test author can mock the module definition as they please, but the default behaviour should not prevent other tests from running, as it does now.

Defined suffix-less index.js

---

README.md
android/build.gradle
android/src/main/java/com/dieam/reactnativepushnotification/ReactNativePushNotificationPackage.java
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java
package.json

Hello,
React Native a new event in the 0.30 version , [`onNewIntent`](https://github.com/facebook/react-native/commit/2fc0f4041ec836c1e1aef1f5d9c77b4f4aba4aae), which allow us to know when the current activity receives a new intent without having to implement a method in `MainApplication` and `MainActivity`.
It simplifies the code a lot, even when implementing the module since we don't need to pass the event from the activity -> application -> module.
I tested it, it works fine.

Use onNewIntent from ActivityEventListener

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java

The new default that was added is 1000ms which is too long. In my experience almost every notification uses the default time of 300ms (as actually documented in the README.md) which is more sensible for incoming messages, whereas 1000ms feels like the start of an alarm / phone call.

Change default vibration time to 300ms.

---

android/build.gradle

This makes it incompatible with other plugins including `react-native-background-geolocation`.

Don't pin down version

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java

Since onNewIntent is a method from ActivityEventListener interface, it just needs to be implemented, not override. It was throwing an error with this method override.

Removes @override onNewIntent

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationRegistrationService.java

When I build 2 apps and both use this module, the `intent` of `sendBroadcast` on each app are the same therefore when the Registration/Notification received in one app the broadcast it sends will be received by all of the apps that listen to the same intent.
This PR solves this problem by adding `package name` prefix.

sendBroadcast: make the intent of broadcast more unique by adding the package name

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationJsDelivery.java
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java
index.js

Make the background listener service start the React JS application (sans Components), and then uses the results of any PushNotification.configure() calls to trigger the JS-based onNotification from the listener service.
This avoids the need to package everything into the Android notification payload to get it to show up, and should hopefully fix a bunch of open issues against this repo.
Note, I haven't explored what's required to get this equivalent functionality working on iOS (and I suspect it may not even be possible at all). But this helps me avoid duplicating functionality on Android and JS by letting me combine it.
I suspect there is additional work that might help combine other native-Android notification processing (RNPushNotificationPublisher and …

Run onNotification() in JS, even when the app isn't running at all.

---

index.js

This has been addressed here: #56
I added the .toISOString(), so there will be no error when scheduling notifications on iOS.

fixed scheduleLocalNotification to work on iOS

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java

Call RNPushNotificationHelper.sendNotification when a notification arrives and app is not running to present a notification to the user

[Android] Remote notifications should be added to the notifications centre when app is not running

---

index.js

When I call `unregister()` and then call `configure()`, since `this.isLoaded` is true already the event listeners will not be set. So the `_onRegister()` and `_onNotification()` callback will not be called either. This PR fixes this by setting `this.isLoaded` to false when calling `unregister()`.

set isLoaded to false when unregister

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java

Sound and color should be passed from the [JSON payload](https://developers.google.com/cloud-messaging/http-server-ref#notification-payload-support) to the notification listener.

Receive sound and color from JSON payload

---

index.js

If `playSound` option is not passed, soundName option is overrided by `'default'`.
therefore, for now, if we want to change `soundName`, we have to pass `playSound: true` explicitly.

Use not default but passed soundName when playSound is not passed

---

component/index.android.js

Please refer to facebook/react-native#10776
This PR fixes the collision when 2 handlers are the same. For instance, in this module's [index.js][1], both remote and local notification use the same handler.
[1]: https://github.com/zo0r/react-native-push-notification/blob/master/index.js#L84-L85

Use event type as the key instead of the handler to store in the handler map

---

index.js

I'm using local notification with badges on iOS, here's a pull request for support. I've sticked to the same syntax. The PushNotificationIOS library expects an integer for the applicationIconBadgeNumber.

Add badge and soundName properties to local notification schedule

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java

java.lang.NullPointerException: Attempt to invoke interface method
'java.util.Iterator java.util.List.iterator()' on a null object
reference
at
com.dieam.reactnativepushnotification.modules.RNPushNotificationListener
Service.isApplicationInForeground(RNPushNotificationListenerService.java
:120)
at
com.dieam.reactnativepushnotification.modules.RNPushNotificationListener
Service.handleRemotePushNotification(RNPushNotificationListenerService.j
ava:96)
at
com.dieam.reactnativepushnotification.modules.RNPushNotificationListener
Service.access$000(RNPushNotificationListenerService.java:25)
at
com.dieam.reactnativepushnotification.modules.RNPushNotificationListener
Service$1.run(RNPushNotificationListenerService.java:63)
at android.os.Handler.handleCallback(Handler.java:739)
at …

Fix crash in our App

---

README.md

Add the npm `--save` flag in the installation documentation
From the [docs](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#step-1):
> --save or --save-dev flag is very important for this step. React Native will link your libs based on dependencies and devDependencies in your package.json file.
This has been discussed in #318 
Probably fixes #361

Add the npm --save flag in the installation documentation

---

README.md

Just added a note in the Readme, to clarify that it is still needed to update AndroidManifest.xml, after `react-native link` in order for scheduled notification to work on Android (PushNotification.localNotificationSchedule). 
References to issues: 
#346  #355

Updated documentation to add a missing note for Android install

---

README.md
index.js

https://github.com/facebook/react-native/pull/8040

added delegate for the new finish method that's in RN 0.38 which calls the completion handler

---

README.md
index.js

React Native added support for the alert title some time ago.
It can be seen in this commit: https://github.com/facebook/react-native/commit/ec74a9696a8864928cab59e40db8b446deb23762#diff-2809d4592d87587e30e146d50d49188d
This closes #608

Add support for notification alert title on iOS

---

README.md
android/build.gradle

Fixes https://github.com/zo0r/react-native-push-notification/issues/682

Add gradle configuration property

---

README.md

* Updated the readme doc, usage of cancel local notifications is clear and simple now.

Clarifying usage for `cancelLocalNotifications`

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java
component/index.android.js
index.js

As discussed in #371 there is no way to remove a notification from the notification centre.
This PR adds a method that removes a notification by id from the centre.

Add clearLocalNotification method

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java

On Android silent push notifications trigger alert with `Notification received` message when app is in background.
If there is no `message` supplied then user should not be alerted with a default message. Otherwise it makes silent push notifications impossible on Android.
At the moment every time a silent push notification is received (while app is in background) user receives an alert with `Notification received` message.
Fixes: https://github.com/zo0r/react-native-push-notification/issues/410

[Android] Remove default alert for silent push notifications

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java
component/index.android.js

Follows the same method signature as the existing one for iOS.
Tested on Android 5.0 and 8.0.

add `checkPermissions` for Android

---

README.md
android/build.gradle
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java
component/index.android.js
index.js

This PR adds Firebase support to this repository. I'm not an Android developer so please feel free to let me know if there's some weirdness on the code. I made this PR as GCM is being outdated and need to be replaced by FCM. In order to do this PR, I followed the steps provided by @Rah1x in #697. Hope this will help!

Add Firebase (FCM) support

---

trouble-shooting.md

Typo fixes in troubleshooting doc

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java

A cleaned up version of https://github.com/zo0r/react-native-push-notification/pull/793

Fix pop initial for firebase

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java

`title` and `body` are special props when coming from GCM/Firebase compat. Their keys are prefixed with `gcm.` which is ignored when `getData()` returns it's data.
We have to use the remote notification APIs to get access to those properties.
I've added these new props before iterating the data bundle so data can override this, making this change backward-compatible.

Fix title and message for Firebase

---

README.md

It wasn't obvious that you have to update AndroidManifest.xml if you want to use localNotificationSchedule(). Updated the commented code in README to make that more clear

update README about localNotificationSchedule()

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java

I added a try catch block in requestPermissions.
This ensure that the app doesn't crash when in background.
It should fix Issue #803.

Fix requestPermissions crash (Issue #803)

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationConfig.java
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java

This PR follows the metadata approach as encouraged by [firebase sdk](https://firebase.google.com/docs/cloud-messaging/android/topic-messaging#edit-the-app-manifest) itself. See the linked issues for details
Fixes https://github.com/zo0r/react-native-push-notification/issues/820 https://github.com/zo0r/react-native-push-notification/issues/814
Closes https://github.com/zo0r/react-native-push-notification/pull/815

Allow configuring notification channel and color through manifest

---

CHANGELOG.md

Use [keepachangelog](https://keepachangelog.com/en/1.0.0/) conventions to provide a clear description of the changes between versions as proposed [here](https://github.com/zo0r/react-native-push-notification/issues/785#issue-340168647).
It is recommended to enforce a workflow where contributors describe changes made in PRs in the changelog as explained [here](https://github.com/react-navigation/react-navigation/pull/4544#issuecomment-399355299).

Standardize Changelog

---

README.md

link command should target the specific pkg to avoid unwanted side effects

react-native link react-native-push-notification

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerServiceGcm.java

Maybe not the best solution in term of code redundancy but it works.
What do you think ?

Added the "old" GCM listener to get compatibility with GCM back

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java

[Android] Allow to set notification's priority, visibility and importance options
[Android] Change default priority to high
[Android] Change default importance to high

[Android] Allow to set notification's priority, visibility and importance options

---

README.md

As specified  in this link: 
https://android-developers.googleblog.com/2018/05/announcing-new-sdk-versioning.html
Prior to version 15 firebase and google-play-services, should have the same version, in our project we specified google-play-services version to 11, but not firebase, so Android builds started to fail, since this was not specified in the docs, I had to research and came across to that article, specifying the same version for both worked like a charm! Also I believe this fixes this [issue](https://github.com/zo0r/react-native-push-notification/issues/830)

Update documentation to avoid falling Androids' build

---

CHANGELOG.md

Document changes for everything in between 3.1.1 -> 3.1.2 for when 3.1.2 is cut.
I figure 3.1.2 instead of 3.2.0 since nothing really to significant added.

3.1.2 Changelog

---

.npmignore

This PR just adds the .git file to the .npmignore so that it is ignored when used. Someone just forgot to add it in at some point.

ignore .git closes #1057

---

android/build.gradle

The fallback variables defined in the build gradle are all undefined
DEFAULT_SUPPORT_LIB_VERSION
DEFAULT_GOOGLE_PLAY_SERVICES_VERSION
DEFAULT_FIREBASE_MESSAGING_VERSION
Edit: not sure why there were downvotes on this, so I have provided a little more clarification.
https://github.com/zo0r/react-native-push-notification/commit/acfa3bf15308e3d7bc7f7ced76c7a11e932d7314
This particular commit Refractors the hard coded variables to the safeGet method fallback, but it seems like the variables above were missed or the changes lost in a merge conflict, this PR fixes this issue and ensures android builds correctly.

Fix undefined fallback variables in build gradle

---

README.md

Updated docs to reflect the official effect of calling the method

Abandon permissions unregisters remote only

---

android/react-native-push-notification.iml

Addresses issue: https://github.com/zo0r/react-native-push-notification/issues/1169
Somehow a reference to a `january.ai` project found its way into the project, breaking android studio builds. This PR removes it.

fix: Remove fishy reference from android project files

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationConfig.java

`getString` returns `null` if mapping does not exist for a key.
(https://developer.android.com/reference/android/os/BaseBundle.html#getString(java.lang.String))
also `createNotificationChannel`
(https://developer.android.com/reference/android/app/NotificationManager#createNotificationChannel(android.app.notificationchanne))
fails if channel name is an empty string.
*update*
A bit more clearer explanation: w/o this fix if channel name is not provided through manifest the `getChannelName` will return `null` and the following call to `createNotificationChannel` (https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L577) will fail with exception, which will be swallowed here …

Properly handle default values of metadata

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java

On Android 6.0 (API level 23) and above in order to reduce battery consumption, the system enters in Doze mode while the device is unused for long periods of time.
While on Doze mode the AlarmManager alarms dont execute exactly on the scheduled time, they are deferred to the next maintenance window. This cause the notifications to show after their scheduled time.
This change adds a new attribute `allowWhileIdle` to allow the notification to be displayed while on doze
This behavior is documented on: https://developer.android.com/training/monitoring-device-state/doze-standby

[Android] Allow to set the notification to executes on idle

---

component/index.android.js

I had a crash due to a conflict with the `react-native-onesignal` package.
Push coming from OneSignal were handled in the `react-native-push-notification` code but the format is not the same.

Add nullchecks for JSON parsing

---

README.md
android/build.gradle

Backwards compatibility with `jetify -r` for pre-AndroidX projects was broken in [this commit](https://github.com/zo0r/react-native-push-notification/commit/30f12eb099ccfc66b72807f79c3c5d34f8f2b290).
This PR makes the AndroidX support backwards compatible again by following the [jetify module maintainers guidance](https://github.com/mikehardy/jetifier#module-maintainers) based on [this commit](https://github.com/react-native-community/react-native-device-info/commit/d448d872906335813d53a7e8f8dc7860ae160c40).

Make AndroidX support backwards compatible

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java
component/index.android.js
example/App.js
example/NotifService.js
index.js

The Abandon Permissions method makes possible to revoke the current token, generating a new one on registration.
Unregister for all remote notifications received via APNS or FCM.
In case many users could be using the same device, Revoke Token will be useful to prevent notifications to the previous user from the device, using it in a logout action for example.
Fixes #864

Added Abandon Permissions method to Android

---

package.json

Version 1.1.0 giving a `No known class method for selector 'didReceiveNotificationResponse'`error

Update push-notification-ios to 1.2.0

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java

I noticed that push notifications received on Android do not show sent date timestamps. 
According to [official docs](https://developer.android.com/reference/android/app/Notification.Builder.html#setShowWhen\(boolean\)) it's off for Android 7 and higher.
Here is example:
This PR enables it by default for every Android version.

Add missing push timestamp for Android 7+

---

README.md

I believe this would be helpful since, from what I can tell, auto linking will not work without doing this.

Add PushNotificationIOS installation instruction link

---

submitting-a-pull-request.md

Fixing typo in pull request submission documentation.

---

index.js

Currently we add notification `id` variable to notification object on iOS only if `userInfo` exists. 
If `userInfo` is not set, `id` is not being set. 
This PR fixes that.
Cheers 🍻

Add notification id to iOS if userInfo doesn't exist

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java

The reason for this PR as that when using `@react-native-firebase/messaging`, background notifications show up with different icons to `react-native-push-notication`. For backwards compatibility, I've added support for empty strings causes no icon customisation on the native notification, which mimics behaviour of the RN firebase messaging module.

Support empty strings as default push notification icons

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java
component/index.android.js
index.js

The rationale behind this PR is that the current functionality with default channel names does not look very professional the end user. Apps can use this new function along with the Manifest setting to disable default channel creation to have fully customised channels.
This has had a fair bit of internal testing and the app using it will be updated for the public soon. I realised after doing this that the `importance` parameter should have used the string mappings already existing, but I don't have time to update that at the moment. Also the typings have not been updated.

Add function createChannel for custom Android channel support

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java

This PR is part of the solution to the following problem:
- Using `@react-native-firebase/messaging` for delivery and handling or remote messages and notifications when the app is killed or in the background
- Using `react-native-push-notification` to display these notifications when the app is in the foreground
- Tapping on a push that arrived in the foreground opens the app but does _not_ send the payload through to RN firebase `messaging().getInitialNotification` or `messaging().onNotificationOpenedApp`
RN firebase messaging stores the remote notification payload and looks it up based on this "message_id" intent extra. The full solution requires minor changes to RN firebase too, which will be submitted as another PR soon.

Add Android messageId to enable integration with react-native-firebase/messaging

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java

Fixes #1356 
We're using multiple push providers and thus need to use a delegate service for handling our notifications.
This PR adds ability to specify a delegate service during instantiation as this library will otherwise throw an NPE when attempting to invoke `getReactNativeHost()` when handling a remote message in RNReceivedMessageHandler.

Add support for specifying a delegate FirebaseMessagingService

---

trouble-shooting.md

* describe briefly the rational of the change, why did you do this (to create new feature, bug fix, add some missing docs etc...)?
It adds some help about why users can be facing a strange problem when local notifications only work if user has remote debugger enabled.
* detail the purpose of the change - **what is the expected change in behaviour**?
To help developers that can have this problem.
It is not changing any piece of code
* state which operating systems are affected
Android and iOS
* provide details on how to test the change
It is not needed

Add help about local notifications problems

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java

This fixes the vibration feature for notification for Android notifications for API >= 26. This pattern is used for the Notif Builder for API < 26 and it appears to work there as well.
Before:
```
<Sending Notif>
2020-10-04 12:37:03.630 1936-29464/? E/VibratorService: vibratorOff command failed (1).
2020-10-04 12:37:03.935 1936-29476/? E/VibratorService: vibratorOff command failed (1).
```
After:
```
<Sending Notif>
2020-10-04 12:07:16.037 1936-4760/? E/VibratorService: vibratorOff command failed (1).
2020-10-04 12:07:16.037 1936-4760/? E/VibratorService: vibratorOn command failed (1).
2020-10-04 12:07:16.438 1936-1936/? E/VibratorService: vibratorOff command failed (1).
```
Have tested this on a physical device as well and it works. This could lead to an obvious extension which is for …

Fix for vibration on notifs for Android API >= 26

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java

Currently it isn't possible to make silent channels, and sending silent notifications to Android > 8 devices.
A playSound option is added to PushNotification.createChannel() to make it possible to create silent channels in Android. The same option exists in PushNotification.localNotification().
Related issues: https://github.com/zo0r/react-native-push-notification/issues/1432 and https://github.com/zo0r/react-native-push-notification/issues/1045

Android: silent channel using playSound flag

---

CHANGELOG.md
README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java
example/NotifService.js
index.js
package.json

As of [push-notification-ios@v1.7.0](https://github.com/react-native-push-notification-ios/push-notification-ios/releases/tag/v1.7.0), these iOS methods are deprecated:
- presentLocalNotification
- scheduleLocalNotification
- cancelAllLocalNotifications
- getScheduledLocalNotifications
This PR replaces those methods appropriately on iOS without changing the API of react-native-push-notification.
This fixes https://github.com/zo0r/react-native-push-notification/issues/1716
alertAction is deprecated as of iOS 10 and is not available in the new addNotificationRequest method.
It should also be noted that push-notification-ios@v1.4.1 had an unmentioned breaking change, requiring users to update their AppDelegate to use UNUserNotificationCenter and to stop using …

Replace deprecated local notification methods on iOS

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationPicturesAggregator.java

Add support for [BigLargeIcon](https://developer.android.com/reference/android/app/Notification.BigPictureStyle#bigLargeIcon(android.graphics.Bitmap)), which is the large icon shown on the upper right when a picture or media notification is expanded (see [here](https://itnext.io/android-notification-bigpicturestyle-1f293e6cabaf) for a splendid explanation).
Currently, when you add a picture to a notification and use largeIcon for preview, when you expand the notification you will see both, the picture and it's same, just smaller preview on the upper right.
I think this doesn't look too nice and it's better to have the largeIcon disappear or set to something else (e.g. the app icon) in expanded view, which this change enables the users to.
That's also the reason why in the code I don't …

implement 'bigLargeIcon' for Android notifications

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java

Add support for using drawable resource as Android local notification small icon.
Default using drawable since Image Asset Studio puts notification icons in there.
fixes #1594

Support using drawable as Android small icon

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java

For https://github.com/zo0r/react-native-push-notification/issues/1801.
This adds hooks to allow easier customization of intent handling and bundle parsing behaviour on Android. This can be used to send notifications sent by 3rd party messaging management platforms that have custom message formats the same onNotification() JS codepath.
See discussion in #1801.

[Android] Add hooks to intent handling and bundle parsing

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java

This is a patch for #1836
I've not tested it.

Handle localization for notification title and body

---

README.md

+ Fix to foreground triggering onNotification on iOS
+ A section covering showing foreground notifications
+ A small comment on notification data/userInfo

Better documentation to PushNotificationIOS integration 

---

README.md

I noticed that `userInfo`/`data` was being returned in the notifications array of the `getScheduledLocalNotifications` but was not properly documented. 
See https://github.com/zo0r/react-native-push-notification/blob/master/index.js#L546
I've also added this property to the @types package https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51720

Document `data` in getScheduledLocalNotifications

---

CHANGELOG.md
index.js

check if react native's app state is unknown to verify if
app came from background

fix(ios): foreground notification property

---

README.md

Fix: indentation of Android code.

Documentation update, fix indentation

---

README.md
android/build.gradle
example/NotifService.js
index.js

Constants come from: https://developer.android.com/reference/android/app/NotificationManager#IMPORTANCE_DEFAULT
Adding these constants as an export would allow users of the library to have clearer code without floating numbers that require going to look at documentation to see what they mean.
This code
```
PushNotification.createChannel(
{
channelId: "default-channel-id", // (required)
channelName: `Default channel`, // (required)
channelDescription: "A default channel", // (optional) default: undefined.
soundName: "default", // (optional) See `soundName` parameter of `localNotification` function
importance: 4, // (optional) default: 4. Int value of the Android notification importance
vibrate: true, // (optional) default: true. Creates the default vibration patten if true.
});
```
would …

Add constants for notification importance

---

index.js

Small one, would have been caught by TypeScript easily 🤷🏻‍♂️

fix: android missing channelId warning should now show

---

android/build.gradle

Fixes an issue when building and running instrumented tests (e.g. Detox) for a React Native project on Android, the following build error was occurring:
```
> Task :react-native-push-notification:mergeExtDexDebugAndroidTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':react-native-push-notification:mergeExtDexDebugAndroidTest'.
> Could not resolve all files for configuration ':react-native-push-notification:debugAndroidTestRuntimeClasspath'.
> Failed to transform firebase-datatransport-18.0.0.aar (com.google.firebase:firebase-datatransport:18.0.0) to match attributes {artifactType=android-dex, dexing-enable-desugaring=false, dexing-is-debuggable=true, dexing-min-sdk=23, org.gradle.status=release, org.gradle.usage=java-runtime}.
> Execution …
```

Fix assembleAndroidTest builds

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java

Resolves https://github.com/zo0r/react-native-push-notification/issues/1729

Fix: Foreground notifications missing small icon

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java

Fix Android 12 (SDK 31) notifications due to missing PendingIntent flags.
Fixes https://github.com/zo0r/react-native-push-notification/issues/2129
I've tested this on a Pixel 5 with Android 12 and a RN app compiled with SDK 31. However, I've only tested local notifications, but I expect that the change should work across all notifications as it is very simple.

Fix Android 12 PendingIntent

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java

**Rationale:**
bigText field should be allowed to have HTML tags as a way to format the message since this has been already supported in android natively for a long time
**Expected behaviour:**
Allows a subset of html tags to be used as outlined [in this android documentation](https://developer.android.com/guide/topics/resources/string-resource#StylingWithHTML). Note that if user did not provided a bigText field but added html tags in message it self, it won't work as message field in iOS does not support HTML tags nor iOS has bigText property
**Testing:**
on bigText field, add some `<br/>` tags and see if it will put the subsequent string to the next line in android.
**Change:**
This is a small change, this merely decorates the bigText as Spanned Text

Allow HTML tags to be used for styling in bigText field only

---

README.md

example:
`const a = b + c ;`
to 
```js
const a = b + c ;
```
> Let me know if i missed anything or stylized anything that should not have been.

Fixed further markdown inconsistencies

---

index.js

For repetition over larger time intervals, the smaller time intervals within `repeatsComponent` need to be set to `true` in order to ensure the notification is delivered at the correct time. Without this fix, iOS scheduled repeating notifications are not sent correctly and do not match the Android behaviour. 
I have tested this PR on my own app in prod and it fixes the issue correctly.
#2147 may be related.

Fix iOS repeated notification timing

---

example/ios/Podfile.lock
example/package.json
package.json

The latest version includes an important fix to prevent the app crashing on iOS 11 devices.
Reference: https://github.com/react-native-push-notification/ios/commit/f2f28cf08f0b6b3f97a3ce799d7b1a662e59edf5

Raise @react-native-community/push-notification-ios version
