README.md
index.js

Sometimes you want to pop manually the initial notification

Add option to popInitialNotification

---

package.json

rnpm will be merged into RN soon, good to get this package compliant.

enabled correct linking from rnpm

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java
component/index.android.js
index.js

android - getInitialNotification - don't expose initialNotification in getConstants, instead be more like IOS and expose a method that returns a promise that is fulfilled with the initial notification or null

Android - get notification data when app is closed

---

index.js

Added userInfo for scheduled iOS local notification

userInfo for scheduled iOS local notification

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationRegistrationService.java

Code to parse some numberic fields was rejecting valid numeric data, and only accepting invalid string types

bug fix to some parsing

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java

This changed in react-native v0.33.0-rc.0
See https://github.com/facebook/react-native/commit/fbd2e139103e3d520f6dfc009d6200f8b8168e35

Add Activity argument to onActivityResult

---

trouble-shooting.md

GCM is an abbreviation for Google Cloud Manager.

Fix GCM typo

---

README.md

Readme: Fix "Pull Requests" title

---

index.js

https://github.com/zo0r/react-native-push-notification/issues/287

Support repeatType for iOS.

---

trouble-shooting.md

Thanks for the library, nice job wrapping PushNotificationIOS & adding a consistent Android option :)
This is a very small update - see https://firebase.google.com/docs/cloud-messaging/concept-options#messages-with-both-notification-and-data-payloads for details.

Update docs for noisy remote push notifications

---

README.md

Just add a tip for letting the options explicit

Update description of localNotificationSchedule

---

README.md

Documentation update following a discussion in https://github.com/zo0r/react-native-push-notification/pull/310

Update documentation on repeating notifications on iOS

---

android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java

The commit a529d01 is broken. Really simple and self explanatory easy fix. I tested it in my app and it launched.

Add import for symbol 'Log'

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java
index.js

Mimic iOS behavior when last day of month is treated properly

Allow monthly repeat

---

package.json
react-native.config.js

This will be required in the next release of React Native. I believe I did this the right way, if anyone thinks there is a more proper way to do this, feel free to contribute! This will close #1125

Moved package.json's rnpm config to react-native.config.js

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationAttributes.java
component/index.ios.js
package.json

PushNotificationIOS has been extracted from React Native Core and will be removed in a future release. This PR migrates to the react-native-community repo.

Update PushNotificationIOS dependency

---

README.md

Hey!
I believe it's should be imported from the repository's library and not using `PushNotificationIOS`.

docs: use package import

---

.npmignore

- https://npmfs.com/package/react-native-push-notification/6.1.3/

[other] Reduce npm package size

---

component/index.android.js

Please note that this merge https://github.com/zo0r/react-native-push-notification/pull/917 doesn't work 
This is a fix to the unsubscribeFromTopic function

unsubscribeFromTopic function fix

---

README.md
android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java

same modules were imported twice.

Remove redundant import statement

---

index.js

should not modify external variables. add deep clone.

(fix) deep clone details and notifications

---

index.js

Remove extra variables.
Led to one look all imports.

(fix) remove unnecessary imports and extra variables.

---

README.md

changed
`PushNotification.cancelAllLocalNotifications()`
to
```javascript
PushNotification.cancelAllLocalNotifications()
```

Fixed Inconsistency in markdown styling.

---

README.md

Updated Firebase reference to show up in English
